version: "3.8"

services:
  jupyter-service: 
    image: jupyter/datascience-notebook:r-4.1.1
    container_name: jupyter-datascience
    restart: always
    environment: 
      - JUPYTER_TOKEN=password
    volumes:
      - ./:/home/work
    ports:
      - 8888:8888
      
  rstudio-service:
    image: rocker/rstudio
    container_name: rstudio-datascience
    environment:
      - PASSWORD=password
    ports: 
      - 8787:8787
    volumes:
      - ./:/home/rstudio

  postgresDB:
    image: postgres
    container_name: pg_container
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: datascience_db
    ports:
      - "5432:5432"
    volumes:
      - ./:/var/lib/postgresql/data

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"

  mongo:
    image: mongo
    container_name: mongo_container
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - ./:/ect/mongo

  mongo-express:
    image: mongo-express
    container_name: express_container
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/ 