set dotenv-load
shell:
    poetry shell
execute:
    poetry run python examples/simple_script.py
execute-dep:
    poetry run python examples/script_with_dep.py 
execute-arg:
    poetry run python examples/script_with_argument.py --nome $NOME